### ISSUE TITLE
Create Fully Kiosk JSON File Template

### ISSUE THREAD

**Issue by ADHDSquir** [dinki/View-Assist#21]
With almost 400 configuration settings for Fully Kiosk, there is a lot of room for variability between setups which can cause unexpected results. We should have a standard known-good JSON config file that users can import to ease setup or to simplify troubleshooting.

**Comment by ADHDSquir** [comment]
Note, Browser Mod makes the following suggesting when it detects it is running in Fully Kiosk:
![fully-screenshot](https://github.com/dinki/View-Assist/assets/1217277/75c1ffb9-37d3-47ed-b1b7-2d15300df3d6)

**Comment by dinki** [comment]
Thanks again
