### ISSUE TITLE
Not all weather providers have a daily forecast

### ISSUE THREAD

**Issue by elwing00** [dinki/View-Assist#23]
Not all weather providers have a "daily" forecast_type.  NWS (https://www.home-assistant.io/integrations/nws/) only has "hourly" and "twice_daily", and I suspect that other weather providers have similar quirks.

One option is updating the documentation to tell folks what to change (line 35 in https://github.com/dinki/View-Assist/blob/main/View%20Assist%20dashboard%20and%20views/views/weather/weather.yaml) or make it a variable like the weather entity itself.

**Comment by dinki** [comment]
Thanks for this.  I've updated with a variable that can be set and as default set it to daily.  Can you try it and confirm my changes work for you with hourly and twice_daily?

**Comment by dinki** [comment]
Confirmed working by @elwing00  ..  Thank you!
