### ISSUE TITLE
Action python_script.set_state not found

### ISSUE THREAD

**Issue by danielholm** [dinki/View-Assist#66]
Just found this amazing project the other day and have successfully got an old android phone configured. I have a followed the tutorials for getting stream, views and sentences to work. However, I get error for a few blueprints where it calls for a python script to set the state. I have yet to find said script, or is it something missing in my Home Assistant instance?

The error is:
 > Action python_script.set_state not found

I use Home Assistant cloud, but that seem to work by my Assist pipeline just as well. But why this error?

**Comment by dinki** [comment]
Hi @danielholm .  Welcome aboard.  Glad to have you.

Looks like you missed this step:

https://github.com/dinki/View-Assist/wiki/View-Assist-control-automations#view-assist-device-control-through-python-set_state

The wiki is a work in progress but really you should start at the top and work your way down to ensure you don't miss anything.  We are available on Discord to help as well.

**Comment by danielholm** [comment]
So I did. Thank you for your quick response! Thought I did indeed following step by step, though apparently I did not. https://github.com/xannor/hass_py_set_state

I will enjoy watching this project evolve. Rather than trying out Pi:s with Mic HAT:s and esp32 with all cables, this is really, really neat. As well as more visually pleasing than my said projects.

Thanks again!
