### ISSUE TITLE
App Switcher Doesn’t Work?

### ISSUE THREAD

**Issue by BakaNode** [dinki/View-Assist#7]
Followed your excellent videos and guide on this page and have everything working great except for the app switcher not doing anything when pressed or even held.

Any advice on how to fix?

**Comment by dinki** [comment]
Hey there.  Thanks for the kind words.  Know that everything is a work in progress so you may be mixing the new with the old.

Can you tell me specifically what you've done and are doing and hopefully I can give better guidance.

**Comment by BakaNode** [comment]
﻿At this time, I have only tried installing the Microsoft launcher thinking that it might be launcher related, but that did not yield any useful results. So I reloaded it from scratch to ensure a clean slate for testing to help assist the best I can.I do indeed have the reboot to logo crash every time I reboot the device and have to quickly disable WiFi to prevent the crash. This seems to be quite problematic when I have to reboot the device every 30 minutes when it goes to sleep and I don’t have any way to wake it up.I also have 2 of these in the same house and had to use the MAC address change to prevent router issues.Darin ShoemakerDirect: 937.205.4551Office: 614.859.2274SUDO//SUPPORTEthical. Technical. Support.On May 15, 2024, at 9:19 AM, Donny F ***@***.***> wrote:﻿
Hey there.  Thanks for the kind words.  Know that everything is a work in progress so you may be mixing the new with the old.
Can you tell me specifically what you've done and are doing and hopefully I can give better guidance.

**Comment by BakaNode** [comment]
The launcher I’m referring to is the Home Screen manager. Every Android device has to run a launcher to setup its visual appeal for icon arrangement, button function, Home Screen features, and etc.I thought the App Switcher may have been broken in whatever launcher was included in this A11 rom so I tried the Microsoft Launcher, I didn’t help the App Switcher though.Darin ShoemakerDirect: 937.205.4551Office: 614.859.2274SUDO//SUPPORTEthical. Technical. Support.On May 15, 2024, at 1:35 PM, Donny F ***@***.***> wrote:﻿
Couple things to note.  You can use the camera shudder to wake the device from sleep.  Just switch its position and the screen should come on.
I turned off auto connect of wifi so when it boots the wifi is off.  See this note:  https://github.com/dinki/View-Assist/wiki/Find-IP-of-Android-device#note-you-may-want-to-turn-off-auto-connect-to-perhaps-lessen-wifi-boot-issues-if-using-the-lenovo-thinksmart-device
Also, sometimes I have to keep the tablet unplugged for a few minutes before restoring power to get it to boot.  All of this is what prompted the warning that this device is not without problem with the A11 ROM.  I plan on getting another to experiment with other ROMs but don't have time to do that while also trying to document View Assist for others.
I'm still unclear what you are referring to for the launcher.  Are you talking about autostarting RTPmic and Wallpanel?  If so, I'm currently using an app called 'Autostart Manager'.  You can find it in the Playstore too.  Also, I find a delay from when the tablet boots to when these apps are launched.
Hope this helps.

**Comment by dinki** [comment]
Excuse my ignorance but what is app switcher?  The thing you get when click the square navigation button?

**Comment by BakaNode** [comment]
> Unfortunately, the app switcher is broken on the Deadman A11 ROM. There is no known fix.

Not sure if this is a Don question or not but I assume there’s no other ROMs we could look into flashing?

**Comment by BakaNode** [comment]
> Excuse my ignorance but what is app switcher? The thing you get when click the square navigation button?

Yes sir, it allows the user to force quit frozen apps and of course quickly switch between them. Think of it as the “swipe up” gesture from iOS.

**Comment by dinki** [comment]
I did notice that as well.  I typically just hold icon, then app info then force stop, restart, clear cache, etc

**Comment by dinki** [comment]
Short of the suggestions I gave earlier, you can try clearing the cache in the bootloader.  You'll need to hold volume up (I think) and apply power and wait for the bootloader menu to show up and then use volume up to move down and volume down for select.  You may already know this and have tried.

I've not had this issue but have found that most of the issues I've had with booting can be resolved by leaving the thing unplugged for a couple minutes and then powering back on.   Outside of this, probably check that mega thread on HA forum.  Device can drive you bonkers.

**Comment by dinki** [comment]
My suggestion now is try the LineageOS ROM.  I have been using it for a few days and it is mostly problem free.  Recommended.

**Comment by dinki** [comment]
Paul wrote an excellent guide for flashing:
https://github.com/pgale/lineage_15.1_Installation_TSV

Join us on Discord.  A good many folks there that can help if you get stuck.  Know that you will need to update your QFIL software to a newer version to be able to flash.
