### ISSUE TITLE
One Question to the mic integrations.

### ISSUE THREAD

**Issue by Coketrd** [dinki/View-Assist#78]
Hi, thankyou for youre time and youre work. I have one question to the mics. How do you integrated the mic´s from the tablets?
Because Streamassist is using a RTSP Camera Server in the background to catch the microphone? I am using KIOSK for example and so i get the speaker to control but not the mic. And the rtsp Camera Server in the back costs performance and didnt working stable. 
How you catched the mic from the devices? This is a point where i am still hanging to find a good solution.

I customized the stream assist a little bit so 

Its possible now send the beep/sst media over the kiosk mode too.

And i integrated the possibility for an Conversation Mode if you want this. So activate the conversation mode with a helper, use the wakeword the first time and after that the mic turn on automaticaly after the tts sentence. And you can do a conversation.

And i can do now with a little workflow  Actionable TTS STT Notifications. For example the assist is saying custom open ai sentence the temperature is low, do you want that i turn on the heater? than its waiting for youre answer, which you can define. 

Thankyou

**Comment by Coketrd** [comment]
> You need to feed Stream Assist an audio stream from an app like IP Webcam. In the IP Webcam app settings, you can set it to only stream audio.
> 
> The [View Assist discord](https://discord.gg/pxp3e8YW) is much more active, so you'd have better luck with troubleshooting tips over there.
> 
> Your Stream Assist customizations sound awesome! There are a couple other people working on their own edits of Stream Assist in the discord, I'm sure they'd be very excited to hear about your work.

Thankyou for youre fast response. i will watch on the discord. Yes i am using the IP Webcam. But only Audio isnt working, is the stream then a other one?

**Comment by dinki** [comment]
Thanks for joining our Discord.  I'll close this one as the conversation happens on Discord.
